//get data
export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const CATEGORY ='CATEGORY';

//cart
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_TO_CART = "REMOVE_PRODUCT_TO_CART";
export const INCR_QUANTITY = "INCR_QUANTITY";
export const DECR_QUANTITY = "DECR_QUANTITY";
export const TOTAL_MONEY = "TOTAL_MONEY";
export const GET_CART = "GET_CART";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
