//get data
export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const CATEGORY ='CATEGORY';

//cart
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
